### ISSUE TITLE
broadcasting performance decreased by 10x

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/CuArrays.jl#134]
I got a slow down of 10x when broadcasting the julia set function.
Luckily, I preserved the fast version in a container:

https://nextjournal.com/sdanisch/cuarrays-fast
https://nextjournal.com/sdanisch/cuarrays-slow

Don't have time to debug this right now, but maybe someone who did commits lately has an idea ;)
You can just click on edit to spin up the gpu instance and get the container + benchmark running (signup code juliacon) :)

**Comment by maleadt** [comment]
Can you run with eg. `nvprof` and `@profile` so that we at least know if the slowdown is GPU or CPU side.

**Comment by vchuravy** [comment]
Fast:

**Comment by vchuravy** [comment]
Ok reproduced on cyclops:

```
vchuravy@cyclops:~$ julia-1.0.0/bin/julia --project=simonfast juliaset.jl 
Benchmarking: CuArray: 
  305.495 μs (33 allocations: 1.50 KiB)
Benchmarking: Array: 
  398.947 ms (0 allocations: 0 bytes)
vchuravy@cyclops:~$ julia-1.0.0/bin/julia juliaset.jl 
Benchmarking: CuArray: 
  3.054 ms (33 allocations: 1.50 KiB)
Benchmarking: Array: 
  397.388 ms (0 allocations: 0 bytes)
```

Note the different environments. SimonFast is saved here https://gist.github.com/vchuravy/9e95dea8a5b4324befbf600f754ccb0b

**Comment by vchuravy** [comment]
Higher register pressure and lots of spills. @maleadt this might be related to no longer inline everything into one kernel.

**Comment by maleadt** [comment]
> no longer inline everything into one kernel

Oh yeah that might be the case. I'll have a look.
FWIW, `JULIA_DEBUG=CUDAnative` is useful to print some additional metrics there. `nvprof` should also have revealed that.

**Comment by maleadt** [comment]
OK, found it. The perf bug indeed surfaced because of disabling the inliner, but is caused by the kernel not getting inlined in the `KernelWrapper` (even though it's just splatting a vararg tuple...). This results in global memory loads/stores because of loading from generic pointers to stack memory where the arguments are stored (because of the calling-convention rewriting).
Will just get rid of the kernel wrapper, if though that will require `return nothing` at the end of kernels again.

**Comment by SimonDanisch** [comment]
Great! Thanks for the help! Sorry for not debugging this more, but just found this when leaving work & wanted to see if this was expected from some recent changes first ;)

>the kernel not getting inlined in the KernelWrapper

Won't any other KernelWrapper like construct have the same issue then?

**Comment by maleadt** [comment]
> Won't any other KernelWrapper like construct have the same issue then?

Yes, but lacking call-site inlining (there's an upstream issue for that), varargs splat are known to be fragile wrt. inference behavior, so not worth filing another issue over.

**Comment by SimonDanisch** [comment]
Fair enough!

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDAnative.jl/pull/254

**Comment by SimonDanisch** [comment]
Thanks for the fast fix!!
![image](https://user-images.githubusercontent.com/1010467/45682778-9e6cd100-bb41-11e8-9209-8c4f576a3246.png)

**Comment by SimonDanisch** [comment]
Lol, seems like it broke Flux, though... :( 
Let me investigate. It's a 701, which is out of resources, no? Maybe that's because it contains some kernels, that don't return nothing - could that be?

**Comment by maleadt** [comment]
Did you use CuArrays/GPUArrays from master? I only ran those test suites, it's possible Flux triggers some otherwise untested code path (and kernel without a `return nothing`).
