### ISSUE TITLE
Automatic creation of contexts on GPU when "using CuArrays"

### ISSUE THREAD

**Issue by einzigsue** [JuliaGPU/CuArrays.jl#15]
HI All,

I just installed CuArrays on top of CUDAdrv. I found "@everywhere using CuArrays" automatically creates GPU contexts, one worker each on device 0. see an example when using 5 workers below.

>  GPU_ID %GPU     GPU_MEM         PID
>    0 	0 	196.8MiB 	169014
>    0 	0 	197.8MiB 	169021
>    0 	0 	196.8MiB 	169023
>    0 	0 	196.8MiB 	169027
>    0 	0 	196.8MiB 	169025
>    1 	0 	0

Do I have control over which device a worker initiates the context on? I think it would be nice that the context can be created in a more controllable way, for example, only when do CUDAdrv.CuContext(CUDAdrv.CuDevice(devInt)). Ideally, it will be great that the following code can create the context only when explicitly called CUDAdrv.CuContext.

```
manager = MPIManager(np=4)
cpus = addprocs(manager)
gpus = [0,0,1,1]
@everywhere CuArrays
for worker in cpus
     @spawnat worker CUDAdrv.CuContext(CUDAdrv.CuDevice(gpus[worker-1]))
end
@parallel (+) for i in 1:4 (xl=cu(rand(10^4,10^4));xr=cu(rand(10^4,10^4)); x=xl*xr;collect(x)) end
```
Cheers
Yue

**Comment by MikeInnes** [comment]
CuArrays doesn't do any context management, so this is coming from [CUDAdrv.jl](https://github.com/JuliaGPU/CUDAdrv.jl). My guess is that when the process starts you want to destroy the default context and then create a new one on the right device.

If you really don't want the context to be created at all on startup, I'm sure CUDAdrv could provide an environment variable for that.

**Comment by MikeInnes** [comment]
I assume you got this figured out, let me know of anything else.
