### ISSUE TITLE
expose cuSolver for Sparse matrices

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/CuArrays.jl#162]
Hi,

From the docs, I have the impression that cusolver can deal with sparse matrices.

Is it a low hanging fruit given the work you already did?

This would be a tremendous addition to `CuArrays`, virtually the only package for sparse matrices on the GPU.

Best regards

**Comment by kshyatt** [comment]
Yes, it is low hanging fruit. So low, it may already be in the process of being grasped ;)

**Comment by kshyatt** [comment]
https://github.com/JuliaGPU/CuArrays.jl/pull/170 it's happening!
