### ISSUE TITLE
Adapting isbits types

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CuArrays.jl#200]
Current Flux with master CuArrays and GPUArrays:
```julia
julia> cu(Flux.onehot(1, 1:3))
ERROR: MethodError: no method matching similar(::Type{CuArray{Float32,N} where N}, ::Type{Float32}, ::Tuple{Int64})
Stacktrace:
 [1] convert(::Type{CuArray{Float32,N} where N}, ::Flux.OneHotVector) at /home/mikeinnes/.julia/packages/GPUArrays/HmVTY/src/construction.jl:67
 [2] adapt_storage at /home/mikeinnes/.julia/packages/CuArrays/PnjcH/src/array.jl:167 [inlined]
...
```

[These definitions](https://github.com/JuliaGPU/CuArrays.jl/blob/77ef17861f246411d3427856bd213ad755f591a6/src/array.jl#L166-L167) have changed at some point; they used to check `isbits` before doing any conversion, since any isbits type (like OneHotVector) is already CUDA-compatible anyway. Clearly there's some compatibility issue in GPUArrays as well.

**Comment by maleadt** [comment]
Probably got lost during refactor because IIRC there weren't any tests or documentation for that behavior.
