### ISSUE TITLE
Feature request: CuArray without memory ownership

### ISSUE THREAD

**Issue by yatra9** [JuliaGPU/CuArrays.jl#203]
Hello!

It would be better if there is a way to construct CuArray without memory ownership from a raw DevicePtr or raw CUDAdrv.Mem.buffer.

I use PyTorch and sometimes want to write a GPU kernel with CuArray.

Now, the inner constructor of `struct CuArrays` (defined in array.jl) calls `Mem.retain(buf)` and `finalizer(unsafe_free!, xs)`,
and there seems no way to construct CuArray without these calls.

It would be great, for example, the constructor of CuArrays takes an additional argument `own` like
`unsafe_wrap(Array, pointer::Ptr{T}, dims; own = false)`

Thank you for advance.

**Comment by maleadt** [comment]
> I use PyTorch and sometimes want to write a GPU kernel with CuArray.

Just add another `retain` call before construction the array such that the refcount never drops to zero?

**Comment by MikeInnes** [comment]
Seems like it'd be reasonable to have an API for this (even if it just does what Tim suggested). @yatra9 I'm sure a PR for something like `unsafe_wrap` would be welcome.

**Comment by yatra9** [comment]
> Just add another `retain` call

Uh... That's a quite practical solution.

> PR for something like `unsafe_wrap` would be welcome.

I'd like to try it.
But, is it acceptable to add a boolean property for `ownership` to `struct CuArray`?
I think that to skip the calls of `Mem.retain(buf)` and `finalizer(unsafe_free!, xs)` in the constructor is not enough because we need to consider the copy constructor, isn't it?

**Comment by MikeInnes** [comment]
Yes, that would be fine. Just write `unsafe_wrap() = ` in front of whatever you're doing now :)
