### ISSUE TITLE
Feature Request: batched matrix trace

### ISSUE THREAD

**Issue by Roger-luo** [JuliaGPU/CuArrays.jl#207]
I'm trying to implement batched matrix trace `batch_tr` on `CuArray{T, 3}`, where the last dimension is treated as batch dimension.

I find `tr(::CuArray)` actually uses the slicing with `diagind`, however, I didn't find any overload for `getindex` in `CuArrays` for `UnitRange` or `AbstractRange`, so the question is how `CuArray` implement this `getindex`?

Since `batched_tr` requires to sum over several `diagind` area with offsets I'm wondering if I could implement a `batched_diagind` and use `sum` directly. Any suggestions? 

---

A practical case for using this function is calculate the matrix trace over a large batch of small matrix

```julia
A = rand(3, 3, 1000)
dA = cu(A)
batched_tr(dA)
```

I think this is quite suitable to calculate via GPU.

A naive implementation is to use `view`

```julia
batched_tr(A::CuArray{T, 3}) where T = sum(view(A, i, i, :) for i in 1:size(A, 1))
```

This is still 10x slower than CPU version

```julia
batched_tr(A::AbstractArray{T, 3}) where T = batched_tr!(A, fill!(similar(A, (size(A, 3), )), 0))

function batched_tr!(A::AbstractArray{T, 3}, B::AbstractVector{T}) where T
    @boundscheck size(A, 1) == size(A, 2) || error("Expect a square matrix")
    @boundscheck size(A, 3) == length(B) || error("Batch size mismatch")
    @inbounds for k in 1:size(A, 3), i in 1:size(A, 1)
        B[k] += A[i, i, k]
    end
    B
end
```

**Comment by Roger-luo** [comment]
Yes, this one is what I wanted. However, I can't find the documentation for it. GPUArrays.jl's doc seems broken. How do you know this function... @yatra9

**Comment by maleadt** [comment]
That's just the GPUArrays equivalent to `@cuda`, ie. writing a custom kernel.

**Comment by Roger-luo** [comment]
I see. Do you want me to make a PR for this? like `tr_strided_batched` (following the `gemm_batched_strided`)

Or including batched routines in a separated package is preferred?

**Comment by maleadt** [comment]
This is not my area of expertise, so I don't know how stuff is typically done with these operations. Maybe @andreasnoack can chime in. Wrt. `gemm_batched_strided`, I would have expected that users wouldn't need to call that method explicitly, and high-level interfaces would need to be adapted in order to dispatch to it automatically?

**Comment by Roger-luo** [comment]
Yes, I have a package called `Batched` with dependent types defined for batched strided arrays: https://github.com/Roger-luo/Batched.jl

@MikeInnes suggested to having routines defined in upstream in https://github.com/FluxML/NNlib.jl/issues/76

**Comment by Roger-luo** [comment]
I have packed the routines here: https://github.com/Roger-luo/BatchedRoutines.jl
