### ISSUE TITLE
unsupported keyword argument "flipkernel"

### ISSUE THREAD

**Issue by gzhang8** [JuliaGPU/CuArrays.jl#216]
I got this error when running this Flux [example](https://github.com/FluxML/model-zoo/blob/master/vision/mnist/conv.jl) on GPU. I am using all packages from add. Is there a lag between versions?

```
MethodError: no method matching ∇conv_data!(::CuArray{Float32,4}, ::CuArray{Float32,4}, ::CuArray{Float32,4}, ::CuArray{Float32,4}; pad=(0, 0), stride=(1, 1), dilation=(1, 1), flipkernel=0)
```

**Comment by maleadt** [comment]
That's probably an issue with Flux.jl then (can't be sure since you didn't post the backtrace).

**Comment by maleadt** [comment]
Probable https://github.com/JuliaLang/METADATA.jl/pull/20147 fixes this.

**Comment by MikeInnes** [comment]
Yeah, this was on NNlib.

In the new year I want to basically start doing PkgEval for GPU so we can avoid some of the fragility we have here currently.
