### ISSUE TITLE
Require CUDA libraries unconditionally

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CuArrays.jl#221]
https://github.com/JuliaGPU/CuArrays.jl/blob/master/src/solver/CUSOLVER.jl#L14-L16

maybe we should just require these to be present unconditionally -- they're part of the CUDA toolkit

**Comment by kshyatt** [comment]
Is this solved now that we have CUSPARSE in the main repo or no?

**Comment by maleadt** [comment]
No; what I meant is that we "support" building CuArrays only providing some libraries (eg. CUBLAS and CUSOLVER) and not others (say, CUSPARSE) in which case certain submodules (CuArrays.CUSPARSE) will be unavailable. Since CuArrays.CUSOLVER depends on CuArrays.CUSPARSE, not having the latter would break the former. We should probably get rid of this functionality and just require all libraries that are shipped with CUDA (ie. everything but CUDNN) to be present unconditionally.

**Comment by kshyatt** [comment]
Yeah, makes sense. Thanks for the explanation!

**Comment by maleadt** [comment]
This has been implemented.
