### ISSUE TITLE
Is there documentation?

### ISSUE THREAD

**Issue by kehlert** [JuliaGPU/CuArrays.jl#238]
Sorry if it's obvious, but is there documentation? It looks like there isn't any in the repo, and the only bit I found was in a pull request and in a blog post or two. Looking forward to using the code.

Thanks!

**Comment by maleadt** [comment]
Documentation is sparse indeed, and we're starting to work on some tutorials. In general though, you can use CuArrays as if it were any other library implementing AbstractArray so much of the Base documentation should suffice.
