### ISSUE TITLE
CUSPARSE not defined

### ISSUE THREAD

**Issue by kehlert** [JuliaGPU/CuArrays.jl#247]
I installed CUDA 8.0 and built CuArrays successfully. I then ran
```
using CuArrays
using CuArrays.CUSPARSE
```
According to some examples I found and the CuArray test code I read, I think that's the correct code. However, I got the error
```
UndefVarError: CUSPARSE not defined
```
By the way, if I just run
```
using CuArrays
x = rand(Float32, n)
d_x = CuArrays.CuArray(x)
```
Then the code runs successfully.

**Comment by maleadt** [comment]
What was the output of the build step? Which version of CuArrays are you using? Can you post `CuArrays/deps/ext.jl`?

**Comment by kehlert** [comment]
Here is the build output
```
julia> Pkg.build("CuArrays")
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building CUDAdrv ─────────→ `~/.julia/packages/CUDAdrv/LC5XS/deps/build.log`
  Building LLVM ────────────→ `~/.julia/packages/LLVM/tPWXv/deps/build.log`
  Building CUDAnative ──────→ `~/.julia/packages/CUDAnative/AGfq2/deps/build.log`
  Building Conda ───────────→ `~/.julia/packages/Conda/uQitS/deps/build.log`
  Building FFTW ────────────→ `~/.julia/packages/FFTW/p7sLQ/deps/build.log`
  Building CuArrays ────────→ `~/.julia/packages/CuArrays/f4Eke/deps/build.log`
```

To install CuArrays, I just ran `Pkg.add("CuArrays")` within the last hour, so presumably it's the most recent version.

Here is the output of `CuArrays/deps/ext.jl`
```
# autogenerated file, do not edit
const libcufft = "/usr/local/cuda-8.0/lib64/libcufft.so"
const libcublas = "/usr/local/cuda-8.0/lib64/libcublas.so"
const configured = true
const libcusolver = "/usr/local/cuda-8.0/lib64/libcusolver.so"
const libcurand = "/usr/local/cuda-8.0/lib64/libcurand.so"
const libcudnn = nothing
```

Also, I tried `using CuArrays.CURAND` and that works fine. And I checked that cuSPARSE is in CUDA 8.0, and it indeed is.

**Comment by maleadt** [comment]
Oh you are using a released version. Support for CUSPARSE is very recent, and isn't part of a released version of CuArrays yet. Try the master branch, since a new tag might take a while (it's being blocked on Flux being incompatible with CuArrays).

**Comment by kehlert** [comment]
I see, thank you very much for your help.
