### ISSUE TITLE
Uncoupling Flux/CuArrays

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CuArrays.jl#249]
Would be good to unblock our Flux/CuArrays releases; posting this so everything is clear from my side and we can discuss what needs to happen beyond that.

Before the holidays I implemented @vchuravy's idea of having separate GPU manifests for the model zoo, so that's now safe. I also checked Flux master against the GPU stack, so that should be safe to tag right now.

Still, it's unfortunate that we can't change break CuArrays without also making a Flux release (and this only to meet the low-ish standard of having the latest releases work; pinned Flux or CuArrays versions can still cause problems). @KristofferC suggests having a `VERSION` in CuArrays, and we can do something this in Flux:

```julia
if CuArrays.API_VERSION != 4
  @warn "Please pin CuArrays@0.4"
```

This doesn't feel like an ideal solution to me, but it's probably better than what we have. If no one has any better ideas I suggest we go ahead with that and do a round of testing and tagging.

**Comment by maleadt** [comment]
Such a global VERSION variable wouldn't be available for older versions though. That'd be a good indicator the version is too old, I guess. Why not use Pkg, or other code loading mechanisms (if they know versions)? Or, alternatively but still DRY, we could use the `version` metadata that is part of Project.toml.

**Comment by MikeInnes** [comment]
That would be the obvious thing, but unfortunately after asking around no one seems to know how to do it; that information must exist somewhere but it seems like the pkg machinery throws it out pretty quickly. But if someone wants to figure it out then I'd be on board.

There's no version in CuArrays project.toml currently, we could add one in just as well as adding it to the module. I don't think that gives better guarantees in terms of keeping in sync with the actual package version, but that might improve once attobot3 arrives. It's worth considering if we want to version the internal and user-facing APIs separately, but I doubt that we do.

**Comment by KristofferC** [comment]
Of course it is possible to get it using Pkg, it just doesn't have a nice interface.

```
julia> import Pkg, UUIDs

julia> p = Pkg.Types.EnvCache();

julia> cuarrays = p.manifest[UUIDs.UUID("3a865a2d-5b23-5a0f-bc46-62713ec82fae")];

julia> cuarrays.version
"0.8.1+"
```

**Comment by MikeInnes** [comment]
Another case worth considering is when a user loads cuarrays and then activates a different project. I'm not sure if `pathof` is robust to that case either though.

**Comment by maleadt** [comment]
This is solved now, with the CUDAapi changes.
