### ISSUE TITLE
Clean-up tutorial section in README

### ISSUE THREAD

**Issue by ianshmean** [JuliaGPU/CuArrays.jl#265]
https://juliagpu.gitlab.io/CuArrays.jl/intro.html

**Comment by maleadt** [comment]
That URL doesn't work indeed, but where did you get it from? The README correctly links to https://juliagpu.gitlab.io/CuArrays.jl/tutorials/intro.html

**Comment by ianshmean** [comment]
The very bottom of the page. I still see the broken link

**Comment by KristofferC** [comment]
The whole tutorial section in the bottom seems a bit redundant with the introduction on the top.

**Comment by maleadt** [comment]
Yes, that part needs some clean up. I quickly edited the link, for now.
