### ISSUE TITLE
Eagerly put objects back in the pool

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CuArrays.jl#270]
Basically, something like https://github.com/JuliaGPU/CuArrays.jl/pull/226, but more careful and with actual uses in CuArrays.jl. Some backstory.

We now depend on the Julia GC to collect `CuArray` objects before they end up in the pool again. This is not optimal, and compounded by the fact that the Julia GC doens't know about the GPU's memory pressure. As a result, we kind-of rely on hitting a GPU OOM before collecting dead arrays and putting them back into the pool: https://github.com/JuliaGPU/CuArrays.jl/blob/8525a9de7a8da922b0fc4be5783c5bdc5fb8a7a6/src/memory.jl#L254-L256

On the other hand, we often _know_ that arrays are unused and could be put back into the pool again. For example: https://github.com/JuliaGPU/CuArrays.jl/blob/0384d2530f64d808385bc67b8c1cf9f6b73e1c9a/src/solver/dense.jl#L126-L138

One option is to call `finalize`, but that is a pretty slow call and shouldn't be used in performance critical code. Instead, we should have a call to eagerly "free" objects (from the perspective of CuArrays.jl) and put them back into the pool. For example, the `geqrf!` method above would then free its `buffer` before returning. To prevent use of early-freed arrays, we should probably wipe the memory buffer handle (eg. set to NULL or some other sentinel value). Care should be taken to deal with ownership (not support this call when we don't own the `CuArray`? make sure the CUDAdrv refcount is 1?).

**Comment by maleadt** [comment]
cc @SuperFluffy -- would be good to have a use-case or benchmark.

**Comment by KristofferC** [comment]
The common way of doing this is (of course) with the `do` syntax, but this will likely make the code a lot uglier and more "indent"-y.

**Comment by maleadt** [comment]
Implemented both.
