### ISSUE TITLE
Tutorial Link Failing

### ISSUE THREAD

**Issue by mattcbro** [JuliaGPU/CuArrays.jl#272]
It's a shame too,  since Tim's tutorial is superlative with useful examples and graphs.

https://juliagpu.gitlab.io/CuArrays.jl/tutorials/intro.html

**Comment by KristofferC** [comment]
Still fails.

**Comment by maleadt** [comment]
Yeah, it takes a while for the build on `master` to finish and deploy, and I didn't know for sure how the link would look. https://juliagpu.gitlab.io/CuArrays.jl/tutorials/generated/intro/ works, just need to update the README.
