### ISSUE TITLE
How to write generic CPU/CUDA code? 

### ISSUE THREAD

**Issue by dfdx** [JuliaGPU/CuArrays.jl#283]
(partially duplicate of [this post](https://discourse.julialang.org/t/best-way-to-deal-with-broadcasting-of-intrinsics-on-cuarrays/20522) on Discourse)

Let's say, I want to write a function like this: 

```
logistic(x::Number) = 1f0 / (1f0 + exp(-x))
```
It works fine when broadcasting on normal `Array`s, however for `CuArray`s we have to write instead: 

```
logistic(x::Number) = 1f0 / (1f0 + CUDAnative.exp(-x))
```
We can overload `broadcasted` for this specific function, but doing it for every single function would be a mess. 

Another way to deal with it is to make whole-array definitions: 

```
logistic(x::AbstractArray) = 1f0 ./ (1f0 .+ exp.(-x))
logistic(x::CuArray) = 1f0 ./ (1f0 .+ CUDAnative.exp.(-x))
```
The downside is that now we have lost all the advantages of broadcasting. 

Is there a way to tell CuArrays to use a specific version of a function when broadcasting over CUDA array? `cufunc()` seems to be relevant here, but without docs it's hard to infer correctly. If it's not possible, what's the recommended way to write generic code?

**Comment by charleskawczynski** [comment]
I think that [Cassette][https://github.com/jrevels/Cassette.jl/] claims to offer a solution for this. In fact, this precise sort of example is discussed in this [video][https://www.youtube.com/watch?v=_E2zEzNEy-8] however, I've not been able to get a working example. My current attempt looks like this:

```
using CUDAdrv, CUDAnative, CuArrays
import Cassette: @context, @overdub, overdub
@context GPUCtx
@context CPUCtx
overdub(::GPUCtx, ::typeof(exp), x) = CUDAnative.exp(x)
overdub(::CPUCtx, ::typeof(exp), x) = exp(x)
x_ca = cu(rand(5,5))
x_a = rand(5,5)
f(x) = 1 + exp(x+1)
fx_ca = @overdub(GPUCtx(), f.(x_ca))
fx_a = @overdub(CPUCtx(), f.(x_a))
```

I'm running into the following error:
`ERROR: LLVM error: Program used external function '__nv_expf' which could not be resolved!`

**Comment by maleadt** [comment]
You could use `@cufunc`: https://github.com/JuliaGPU/CuArrays.jl/blob/f5cbcfcf329b7e15a9bbbf0f344c5613a83e7148/test/base.jl#L80-L95

Cassette isn't ready to overdub GPU code yet, see https://github.com/JuliaGPU/CUDAnative.jl/pull/334

**Comment by dfdx** [comment]
> You could use `@cufunc` as demonstrated in the tests (docs are lacking indeed):

Indeed, it seems to solve the issue:
```
julia> using CuArrays

julia> logistic(x::Number) = 1f0 / (1f0 + exp(-x))
logistic (generic function with 1 method)

julia> CuArrays.@cufunc logistic(x::Number) = 1f0 / (1f0 + exp(-x))

julia> logistic.(rand(5))
5-element Array{Float64,1}:
 0.5802589498989126
 0.6888046620677325
 0.6026124910853926
 0.7232382041304661
 0.6672557044828792

julia> logistic.(rand(5) |> cu)
5-element CuArray{Float32,1}:
 0.5367112 
 0.727269  
 0.56458366
 0.6493758 
 0.5515733
```
But what exactly `@cufunc` does? From the code I understand that: 

1. It uses MacroTools to replace in function definition all occurrences of `exp`, `log`, etc. with their libdevice counterparts.
2. It defines a new function `cuname` (e.g. `culogistic`). 

Does CUDAnative then automatically find `cu[...]` version of a function when broadcasting over CuArrays? 

-------

I actually have [`cuda_compatible`](https://github.com/dfdx/Yota.jl/blob/cuda-example/src/cuda.jl#L51-L57) function which uses Cassette to recursively replace all "dangerous" functions, which for my case is more flexible than using a macro. It would be great if I could tell CUDAnative/CuArrays to use my definition when broadcasting over GPU array, but simply adding `cu[...]` function doesn't seem to work:

```
julia> using CuArrays

julia> using CUDAnative

julia> logistic(x::Number) = 1f0 / (1f0 + exp(-x))
logistic (generic function with 1 method)

# attempt to define my implementation for CuArrays
julia> culogistic(x::Number) = 1f0 / (1f0 + CUDAnative.exp(-x))
culogistic (generic function with 1 method)

julia> logistic.(rand(5))
5-element Array{Float64,1}:
 0.6642091041578932
 0.6087629482443389
 0.6357307781130886
 0.7234209603557089
 0.7275500830866266

julia> logistic.(rand(5) |> cu)
┌ Warning: calls to Base intrinsics might be GPU incompatible
│   exception =
│    You called exp(x::T) where T<:Union{Float32, Float64} in Base.Math at special/exp.jl:75, maybe you intended to call exp(x::Float32) in CUDAnative at /home/slipslop/.julia/packages/CUDAnative/Mdd3w/src/device/libdevice.jl:90 instead?
│    Stacktrace:
│     [1] exp at special/exp.jl:75
│     [2] #23 at /home/slipslop/.julia/packages/GPUArrays/t8tJB/src/broadcast.jl:49
└ @ CUDAnative ~/.julia/packages/CUDAnative/Mdd3w/src/compiler/irgen.jl:68
5-element CuArray{Float32,1}:
 0.61980796
 0.65715253
 0.7048175 
 0.5884298 
 0.7253468
```

**Comment by vchuravy** [comment]
`@cufunc` is defined here: https://github.com/JuliaGPU/CuArrays.jl/blob/b9fb82d599d1feeef40450e6378eaf5f652d26f3/src/broadcast.jl#L37-L59

The important bit is that you define `cufunc(::typeof(f)) = cuf` for broadcasting.
And if you want `@cufunc` to recognize `culogistic`, push the symbol into the right global list.

**Comment by datnamer** [comment]
There's also this for the more general case of your issue title https://github.com/vchuravy/GPUifyLoops.jl

**Comment by dfdx** [comment]
> And if you want `@cufunc` to recognize `culogistic`, push the symbol into the right global list.

Can you elaborate on this? Both of the following examples seem to work without modifying any global lists in CuArrays:

```julia
# using manually defined culogistic
using CuArrays
using CUDAnative

logistic(x::Number) = 1f0 / (1f0 + exp(-x))
culogistic(x::Number) = 1f0 / (1f0 + CUDAnative.exp(-x))
CuArrays.cufunc(::typeof(logistic)) = culogistic

logistic.(rand(5))
logistic.(cu(rand(5)))
```
```julia
# using @cufunc
using CuArrays

logistic(x::Number) = 1f0 / (1f0 + exp(-x))
CuArrays.@cufunc logistic(x::Number) = 1f0 / (1f0 + exp(-x))

logistic.(rand(5))
logistic.(cu(rand(5)))
```

**Comment by vchuravy** [comment]
One level of indirection will break your example.

```
using CuArrays
using CUDAnative

logistic(x::Number) = 1f0 / (1f0 + exp(-x))
culogistic(x::Number) = 1f0 / (1f0 + CUDAnative.exp(-x))
CuArrays.cufunc(::typeof(logistic)) = culogistic

CuArrays.@cufunc myfun(x)
   logistic(x)
end

myfun.(rand(5))
myfun.(cu(rand(5)))
```

whereas
```
using CuArrays

CuArrays.@cufunc logistic(x::Number) = 1f0 / (1f0 + exp(-x))
CuArrays.@cufunc myfun(x)
   logistic(x)
end

myfun.(rand(5))
myfun.(cu(rand(5)))
```
 will work in either case.

**Comment by dfdx** [comment]
Indeed! Thanks for your answers and examples, guys!
