### ISSUE TITLE
Error with permutedims

### ISSUE THREAD

**Issue by jdnz** [JuliaGPU/CuArrays.jl#30]
It seems permutedims is not correctly permuting CuArrays in some cases. For example:
```
julia> e = cu(rand(2, 2, 2))
2×2×2 CuArray{Float64,3}:
[:, :, 1] =
 0.223654  0.428071
 0.498901  0.423364

[:, :, 2] =
 0.257477  0.138125
 0.612776  0.565442

julia> permutedims(e, (3, 1, 2))
2×2×2 CuArray{Float64,3}:
[:, :, 1] =
 0.223654  0.257477
 0.428071  0.138125

[:, :, 2] =
 0.498901  0.612776
 0.423364  0.565442

julia> permutedims(collect(e), (3, 1, 2))
2×2×2 Array{Float64,3}:
[:, :, 1] =
 0.223654  0.498901
 0.257477  0.612776

[:, :, 2] =
 0.428071  0.423364
 0.138125  0.565442
```
where it appears CuArrays has implemented the permutation (2, 3, 1) instead. As an aside it would be useful if CuArrays allowed the square brackets notation of the permutation [3, 1, 2], as this is what the docs of Base.permutedims suggest.

**Comment by MikeInnes** [comment]
Thanks for reporting! This is fixed on master.

**Comment by jdnz** [comment]
Great, works now, thanks!
