### ISSUE TITLE
CuArrays Does not load.  Requires TimerOutputs in its dependencies

### ISSUE THREAD

**Issue by mattcbro** [JuliaGPU/CuArrays.jl#300]
Just recently after a Pkg.update()  CuArrays stopped loading with the following cryptic message:

```
julia> using CuArrays
[ Info: Precompiling CuArrays [3a865a2d-5b23-5a0f-bc46-62713ec82fae]
ERROR: LoadError: LoadError: ArgumentError: Package CuArrays does not have TimerOutputs in its dependencies:
- If you have CuArrays checked out for development and have
  added TimerOutputs as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with CuArrays

```
Pkg.resolve() didn't do anything to help this.  I'm on linux mint 19,  working with an Nvidia 1080 GTX card.

The problem seems to fix itself it you do a
`Pkg.add("TimerOutputs")`

**Comment by maleadt** [comment]
Ah, probably happens because I forgot to add TimerOutputs to REQUIRE (only added it to Project.toml)...

**Comment by maleadt** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/22378.
