### ISSUE TITLE
wrong result on argmax

### ISSUE THREAD

**Issue by chengchingwen** [JuliaGPU/CuArrays.jl#304]
the result of `argmax` is wrong when there are negative values. looks like its running on the absolute value.

the MWE
```julia
using CuArrays

a = cu(collect(1:10))

argmax(a) # is 10
argmax(-a) # is also 10
argmax(collect(-a)) # is 1

```

**Environment details (please complete this section)**
Details on Julia:
```
# please post the output of:
versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Julia packages:
 - CuArrays.jl: v1.0.1

CUDA: toolkit and driver version
CUDA 9.2
NVIDIA-Linux-x86_64-410.78

**Comment by maleadt** [comment]
Looks like the CUBLAS submodule implements `argmax` with `iamax`, which finds the maximum magnitude.

```
diff --git a/src/blas/highlevel.jl b/src/blas/highlevel.jl
index c675412..2b88ec8 100644
--- a/src/blas/highlevel.jl
+++ b/src/blas/highlevel.jl
@@ -47,9 +47,6 @@ function LinearAlgebra.axpy!(alpha::Number, x::CuArray{T}, y::CuArray{T}) where
     axpy!(length(x), convert(T,alpha), x, 1, y, 1)
 end
 
-Base.argmin(xs::CublasArray{<:CublasReal}) = iamin(xs)
-Base.argmax(xs::CublasArray{<:CublasReal}) = iamax(xs)
```

Looks like we'll need a custom kernel. Or finally add a proper `reduce` implementation to build `findmax`/`findmin`/ on.

**Comment by chengchingwen** [comment]
Are there any reasons for using `iamax` here?

**Comment by maleadt** [comment]
I don't think so, it seems wrong (as shown by your example).

**Comment by findmyway** [comment]
Also `argmax(x, dims)` will fall back to `Base`, someone may consider to fix it together.

**Comment by kraftpunk97** [comment]
@maleadt Absolute beginner in CUDA here. I've looked at some approaches (that may be basic) that work for vectors, but I'll like to extend them to N-dimensional matrices by taking a applying the argmax operation to one vector at a time. Will that work, at least for the time being?

**Comment by kraftpunk97** [comment]
pinging @maleadt

**Comment by maleadt** [comment]
We still need a working version of argmin/argmax before generalizing to N-dimensional vectors. Doing so one vector at a time would be pretty slow, but better then nothing.

**Comment by chengchingwen** [comment]
@kraftpunk97 I guess you could start with some parallel reduction algorithm and the `reduce` implementation.

**Comment by CarloLucibello** [comment]
I was hit by this bug as well. Would it make sense, as a workaround, to modify the implementations as follows?
```julia
Base.argmin(xs::CublasArray{<:CublasReal}) = iamin(xs .- minimum(xs))
Base.argmax(xs::CublasArray{<:CublasReal}) = iamax(xs .- minimum(xs))
```
This would be (twice?) slower but at least we ensure correctness

**Comment by CarloLucibello** [comment]
An alternative temporary fix, which also allows to support `dims`, is to just fallback to cpu ()
```julia
Base.argmin(xs::CublasArray{<:CublasReal}; dims=:) = Base.argmin(xs, dims=dims)
```

**Comment by xukai92** [comment]
I believe this bug would have unexpected effects in many places. I meet it when using `Flux.onehot` on a vector before `softmax`, and I was supervised by the accuracy of my model for a while (which in fact was simply bad but werid). I'd like to make a PR to fix this. Which temporay fix do you think make sense here to go into master for now? @maleadt

**Comment by maleadt** [comment]
With the new findmax it's easy enough to implement argmax, although only the case without a dims keyword. Is that enough for the Flux usecase?

**Comment by xukai92** [comment]
Yes, `Flux.onehot` works as expected now.

**Comment by xukai92** [comment]
But for some reason the operation is very slow:
```julia
x = randn(10, 200)
@btime Flux.onecold($x)
# 129.212 μs (1446 allocations: 41.66 KiB)
x = x |> gpu
@btime Flux.onecold($x)
# 23.816 ms (48492 allocations: 1.56 MiB)
```

**Comment by chengchingwen** [comment]
@xukai92 probably because `onecold` use scalar index, we might still need a `findmax/min` with `dim` keyword supported.

**Comment by maleadt** [comment]
That's incoming: https://github.com/JuliaGPU/CuArrays.jl/pull/500
