### ISSUE TITLE
A_mul_Bc! gives error

### ISSUE THREAD

**Issue by jdnz** [JuliaGPU/CuArrays.jl#31]
I'm having some problems with A_mul_Bc! For example:
```
julia> a0 = cu(rand(1,1) + im*rand(1,1));
julia> ar = cu(rand(1,1) + im*rand(1,1));
julia> en = cu(rand(1,1) + im*rand(1,1));
julia> A_mul_Bc!(en, ar, a0)
ERROR: ReadOnlyMemoryError()
```
For larger matrix sizes julia seg faults in some cases. At the same time, other types of A_mul_B seem to work fine.

**Comment by MikeInnes** [comment]
As far as I can tell, we're just [missing the one-line definition](https://github.com/JuliaGPU/CuArrays.jl/blob/35861766d2dd99dd8f4b03c0101f420cbfa06224/src/blas/highlevel.jl#L123) for this method. Any chance you could add it in?

**Comment by jdnz** [comment]
Right, thanks, I made a pull request.
