### ISSUE TITLE
RFC: Rename CuArrays.CURAND.curand -> CuArrays.CURAND.rand

### ISSUE THREAD

**Issue by mohamed82008** [JuliaGPU/CuArrays.jl#310]
Following up on a discussion on Slack, I suggest that `CuArrays` should have its own `rand` function different from `Base.rand`. To avoid namespace confusion though, `CuArrays.rand` should not be exported. A PR is somewhat straight-forward, but I am opening an issue first to get some opinions.

**Comment by maleadt** [comment]
@MikeInnes @vchuravy @kshyatt @andreasnoack 

I was initially opposed, thinking it could be confusing and we should export `curand` instead, but that's pretty similar to `CuArrays.rand`. Besides, we've been doing this anyway for eg. `CUDAnative.sin`.

Note that in the long term we should be moving towards `CuArray{T}(rand, dims)`, but that would need some design consideration and isn't as straightforward (eg. how to implement `rand(1:2, 3)`).

**Comment by MikeInnes** [comment]
CuArrays.rand seems fine to me. `CuArray{T}(rand, ...)` seems kind of backwards to me but I guess it's not that inconsistent with `undef`; though it seems stranger for things like `fill`. `rand(CuArray, ...)` is another option that has some precedent with `similar`.
