### ISSUE TITLE
Avoid scalar fallback for non-contiguous views

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CuArrays.jl#354]
Basically, get rid of: https://github.com/JuliaGPU/CuArrays.jl/blob/be4ef5641c73fb40a6880173a4d630e9a544440a/src/subarray.jl#L34-L35

In order to preserve the semantics of view/SubArray, we can't eagerly gather the noncontiguous memory into a contiguous buffer but probably need some CuSubArray type to implement e.g. broadcast or copy operations using an optimized kernel. Furthermore, we'd also need to support passing these views to kernels, but we can punt on that (i.e. refuse to `adapt`) and have the user copy/materialize the view for now.

cc @ali-ramadhan

**Comment by maleadt** [comment]
nvm

**Comment by ali-ramadhan** [comment]
Awesome, thanks! Note to self: use `similar` which is CPU-GPU compatible.
