### ISSUE TITLE
Memory: high use of gc() in alloc()?

### ISSUE THREAD

**Issue by louisponet** [JuliaGPU/CuArrays.jl#37]
https://github.com/JuliaGPU/CuArrays.jl/blob/12269b828626bf519e442076caf36b5b9582d775/src/memory.jl#L29

Hi, 
I've noticed that after a while, especially when creating a lot of small CuArrays, performance goes down by at least 5 orders of magnitude while creating a new CuArray. If I comment out the line I highlighted, none of this happens. I've also not found any instabilities or crashes happening after uncommenting this line, not even when the memory of the GPU is 99% used. Is there any reason for this gc pass to be there?

**Comment by MikeInnes** [comment]
That function is designed to avoid CUDA's slow malloc where possible, the idea being that doing a GC to free a pointer will be faster than malloc. Of course, for small arrays that may not be true, so you actually want to GC every few allocations (to refill the pool) but not every allocation.

I wrote this allocator by feel, so it would probably be a good idea to get some benchmarks together and get a feel for how it effects them.

**Comment by maleadt** [comment]
The new pool allocated is a little more careful about this. It could use some tuning though, please open an issue with a MWE if you hit a pathological case.
