### ISSUE TITLE
Allow CuArrays to initialise if there is no CUDA/GPU on the system

### ISSUE THREAD

**Issue by tanhevg** [JuliaGPU/CuArrays.jl#371]
Currently an attempt to `using CuArrays` on a system that has no CUDA/GPU will result in an error. As a consequence, if one has a module that uses `CuArrays`, and wants to use some of its functions on a system without a GPU (e.g. debug a model training loop on a toy data set on a laptop on a plane), a separate `.toml` without `CuArrays` has to be created. This can be avoided by wrapping a few lines in the initialiser in a simple try/catch.

**Comment by maleadt** [comment]
Trying a different approach: https://github.com/JuliaGPU/CuArrays.jl/pull/375 and https://github.com/JuliaGPU/CUDAapi.jl/pull/84
