### ISSUE TITLE
Several package tests fail (Julia 1.1, Windows 10 and CUDA 10.0)

### ISSUE THREAD

**Issue by caxelrud** [JuliaGPU/CuArrays.jl#373]
When using CuArrays v1.1, Julia 1.1, Windows 10, "NVIDIA GeForce GTX 1660 Ti" GPU and CUDA toolkit 10.0, I got the following results when testing these packages:
CUDAapi: pass all
CUDAdrv: pass all
GPUArrays: pass all
CUDAnative: Pass:363, Fail:6, Error:1, Broken:1, Total:371 
CuArrays: Pass: 1096, Error:558, Total:1654

### Please, let me know how to solve the problems.

The results are attached
[CuArraysResults_1.txt](https://github.com/JuliaGPU/CuArrays.jl/files/3413898/CuArraysResults_1.txt)

All packages build have no problem.

Version Information:
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Package Information:
 CUDAapi v0.6.3
 CUDAdrv v3.0.1
 CUDAnative v2.2.1
 CuArrays v1.0.2
 GPUArrays v0.7.2

**Comment by zot** [comment]
On my Linux box, the "Batch 2D (in 4D)" test is failing. I'm attaching the full output.

[CuArrays-jl-test-output.txt](https://github.com/JuliaGPU/CuArrays.jl/files/3613297/CuArrays-jl-test-output.txt)

**Comment by maleadt** [comment]
@caxelrud your log doesn't contain any actual error reports, just the summary. Could you re-test on master (using the CuArrays manifest)? Feel free to re-open the issue if you still have problems.

@zot the issues in your log have been fixed on the master branches.
