### ISSUE TITLE
Invalid versions with Adapt

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CuArrays.jl#374]
https://gitlab.com/juliadiffeq/DiffEqFlux-jl/-/jobs/253124717

Does this just need a tag? I see from the Project.toml that the lower bound is the version of Adapt that is not allowed in my CI.

**Comment by maleadt** [comment]
Yeah CuArrays needs a tag. Note that this will be a major release though, since it removes `curand` and friends, so you might need to adjust your Project.toml anyhow.

**Comment by maleadt** [comment]
Actually, we have deprecations so this isn't breaking. I'll tag a minor release.

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/2077
