### ISSUE TITLE
Pkg.test("CuArrays") fails on julia-1.1.1, linux, sm35, sm70, cuda10.1, cudnn7.0.6

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CuArrays.jl#387]
Here are the error logs:

* [gpu=K20,cuda=10.1,cudnn=7.0.6,cuarrays=1.1.0](http://ai.ku.edu.tr/dyuret/cuarrays1.1.0-sm35-cuda10.1-cudnn7.0.6.err.txt)
* [gpu=V100,cuda=10.1,cudnn=7.0.6,cuarrays=1.1.0
](http://ai.ku.edu.tr/dyuret/cuarrays1.1.0-sm70-cuda10.1-cudnn7.0.6.err.txt)

Tests pass on a different setup on AWS (AMI=Knet-1.2.3 in Ohio):
* [gpu=K80,cuda=10.0,cudnn=7.4.2,cuarrays=1.1.0](http://ai.ku.edu.tr/dyuret/cuarrays1.1.0-sm37-cuda10.0-cudnn7.4.2.pass.txt)

**Comment by maleadt** [comment]
`http://ai.ku.edu.tr/dyuret/cuarrays1.1.0-sm35-cuda10.1-cudnn7.0.6.err.txt`
contains
`ccall: could not find function cublasSetMathMode in library /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcublas.so`

looks like something is off with your cluster.

**Comment by denizyuret** [comment]
Yes, it turns out they changed the way cublas is installed in 10.1:
https://devtalk.nvidia.com/default/topic/1047981/cuda-setup-and-installation/cublas-for-10-1-is-missing/

When the sysadmins fixed the installation/path that problem went away.
CUDAapi seems robust to this new path change.

**Comment by maleadt** [comment]
You would probably be running into other issues when using CUDA 8.0, see https://github.com/JuliaGPU/CuArrays.jl/issues/351. I'll fix the CUBLAS one though.
