### ISSUE TITLE
Out of memory during precompile

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CuArrays.jl#39]
I get the following error during precompile on an 8 GPU machine where devices 0 and 3 are fully occupied:
```
ERROR: LoadError: InitError: CUDA error: out of memory (code #2, ERROR_OUT_OF_MEMORY)
Stacktrace:
 [1] macro expansion at /dev/shm/dyuret/.julia/v0.6/CUDAdrv/src/base.jl:148 [inlined]
 [2] CUDAdrv.CuContext(::CUDAdrv.CuDevice, ::CUDAdrv.CUctx_flags) at /dev/shm/dyuret/.julia/v0.6/CUDAdrv/src/context.jl:11\
8
 [3] __init__() at /dev/shm/dyuret/.julia/v0.6/CUDAnative/src/CUDAnative.jl:67
```
Knet always finds the device with the greatest amount of available memory and by default initializes there.  Is there a way to do this with CuArrays manually or automatically?

**Comment by MikeInnes** [comment]
Can you reproduce this just loading `CUDAnative`? I expect that's where the fix needs to be.

**Comment by denizyuret** [comment]
Yes, I can confirm that `using CUDAnative` causes the same problem.  Just fill up the memory of gpu0 and it does not see there is other gpus to use.

**Comment by maleadt** [comment]
Would it be acceptable to specify `CUDANATIVE_INITIALIZE=false` as environment variable to prevent CUDAnative.jl from initializing device 0, and require you to `device!(whatever)` explicitly?
Doing so automatically upon the first API call, ie. how CUDA does it, is tricky, as I don't want to prefix every CUDAnative & CUDAdrv function with a `initialized || do_initialize()` check, nor pay the performance penalty of more automatic schemes (eg. a hook mechanism for `@apicall`).

**Comment by maleadt** [comment]
Adding a simple, well-typed hook turned out not so expensive, so we have full lazy initialization as per CUDA with https://github.com/JuliaGPU/CUDAnative.jl/commit/c36ce1784aca0e783594d15f808f4cf9636f3979

```
$ DEBUG=true julia examples/vadd.jl
┌ Debug: Initializing CUDA for default device 0 after API call
│   name = "GeForce GTX TITAN"
│   apicall = :cuMemAlloc
└ @ CUDAnative init.jl:28
```

Adding an explicit `device!` disables this mechanism.
