### ISSUE TITLE
Type stability w/ and w/o `using CUDAnative`

### ISSUE THREAD

**Issue by dfdx** [JuliaGPU/CuArrays.jl#41]
If I define a module like this:
```
module M

using CuArrays
# using CUDAnative

function cross_entropy_loss(ŷ::AbstractMatrix, y::AbstractMatrix)
    sublosses = -sum(y .* ŷ, 1) .+ CUDAnative.log.(sum(exp.(ŷ), 1))
    return mean(sublosses)    
end

end
```
and then invoke it form REPL  or another file like this:
```
using CuArrays

function main()
    y = CuArray(rand(Float32, 3, 4))
    ŷ = CuArray(rand(Float32, 3, 4))
    M.cross_entropy_loss(ŷ, y)
end
```
I'm getting:

```
ERROR: Broadcast output type Any is not concrete
Stacktrace:
 [1] broadcast_t at /home/dfdx/.julia/v0.6/CuArrays/src/broadcast.jl:34 [inlined]
 [2] broadcast_c at /home/dfdx/.julia/v0.6/CuArrays/src/broadcast.jl:63 [inlined]
 [3] broadcast at ./broadcast.jl:434 [inlined]
 [4] cross_entropy_loss(::CuArray{Float32,2}, ::CuArray{Float32,2}) at /home/dfdx/Downloads/cross_entropy_test.jl:7
 [5] main() at /home/dfdx/Downloads/cross_entropy_test.jl:18
```
`@code_warntype` shows that the function indeed returns `Any`, but the generated code is too complex for me to infer further details.

If we uncomment `using CUDAnative` inside the module, the error disappears. It also disappears if I define `cross_entropy_loss` in the  same module as calling code or if I try to simplify the function. So I won't be surprised if it's not reproducible even in slightly different conditions. 

I'm using Julia 0.6.0 and latest master of both - CuArrays (`67444add60fee8cfcd346ab7c97dd64bfae4b1ba`) and CUDAnative (`997142a0281034e96d53132da631d01e6646ca6b`).

**Comment by MikeInnes** [comment]
Presumably this is because you're trying to use the CUDAnative module without importing it first?

**Comment by dfdx** [comment]
It's imported automatically:

```
using CuArrays

CUDAnative.log.(CuArray(rand(3,4)))  # works fine
```

**Comment by MikeInnes** [comment]
This is a quirk of module loading, if CUDAnative gets loaded anywhere it's visible in `Main`. This isn't something you can rely on though..

```julia
julia> module Foo
       using CuArrays
       @show CUDAnative
       end
ERROR: UndefVarError: CUDAnative not defined

julia> CUDAnative
CUDAnative
```

**Comment by dfdx** [comment]
Ah, I didn't know about this quirk, thanks! I'm still getting weird errors from this function in a larger piece of code, but it seems to be another story. Closing this issue.
