### ISSUE TITLE
Statistics functions (var,std) slow

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CuArrays.jl#411]
var/std seem to fall back on indexing the CuArray, instead of a vectorized implementation:
```
julia> var(c,dims=1)
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays ~/.julia/packages/GPUArrays/J4c3Q/src/indexing.jl:16
1×4 CuArray{Float32,2}:
 0.0646661  0.167767  0.0156315  0.14948
```
This makes it slower than cpu:
```
julia> c1 = rand(1000,1000);
julia> c2 = CuArray(c1);
julia> @time std(c1,dims=1);
  0.001371 seconds (12 allocations: 16.250 KiB)
julia> @time std(c2,dims=1);
  7.945594 seconds (3.01 M allocations: 138.023 MiB, 0.39% gc time)
julia> @time CuArray(std(Array(c2),dims=1))
  0.003153 seconds (23 allocations: 7.661 MiB)
```

**Comment by kshyatt** [comment]
Seems the issue is the scalar indexing in `centralize_sumabs2!`: https://github.com/JuliaLang/julia/blob/6821437630e8a1e027f681eec5c2eabad1024f8d/stdlib/Statistics/src/Statistics.jl#L225

**Comment by an-awesome-guy** [comment]
This in reference to https://github.com/FluxML/Flux.jl/pull/981 var and std is defined in Statistics.jl. If I want to add functions specific to CuArray where should I add them in this package. @MikeInnes

**Comment by maleadt** [comment]
A new `statistics.jl` top-level file would be a good place.

**Comment by CarloLucibello** [comment]
@an-awesome-guy any update on this?
