### ISSUE TITLE
FFTW vs AbstractFFTs

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CuArrays.jl#419]
FFTW is a fairly heavy dependency, including a Conda install. Presumably we don't need the actual FFTW implementations, which is the main thing it provides; could we switch to AbstractFFTs.jl instead?

**Comment by maleadt** [comment]
I think we require FFTW because of the GPUArrays TestSuite, which is part of the main module. Should probably move to GPUArraysTests or something.

**Comment by maleadt** [comment]
Fixed by https://github.com/JuliaGPU/GPUArrays.jl/pull/219 and https://github.com/JuliaGPU/CuArrays.jl/pull/479
