### ISSUE TITLE
`std` with `dims` keyword argument

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CuArrays.jl#443]
Right now, this falls back to base:

```julia
julia> std(cu(rand(10)), dims = 1)
ERROR: scalar getindex is disallowed
```
xref https://github.com/FluxML/Flux.jl/issues/887

**Comment by kshyatt** [comment]
Probably related to https://github.com/JuliaGPU/CuArrays.jl/issues/411

**Comment by MikeInnes** [comment]
Yes, in fact I should probably close this as a dup.
