### ISSUE TITLE
Kernel optimizations

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CuArrays.jl#445]
Several kernels in CuArrays.jl are functional, but pretty slow. This issue is meant to keep track of that, with pointers to relevant material for optimizations:

- [x] `_accumulate!`: slow global-memory reduction, should use `shfl` (https://developer.nvidia.com/gpugems/GPUGems3/gpugems3_ch39.html, https://github.com/JuliaGPU/CUDAnative.jl/blob/04bd0325521404ed1aa4268238b61b002809bbd5/examples/scan.jl)
- [x] `filter`/`findall`: based on boolean indexing, should use (warp-aggregate) atomics (https://devblogs.nvidia.com/cuda-pro-tip-optimized-filtering-warp-aggregated-atomics/)

Not that this is issue is not meant to document kernels that currently fall back to scalar indexing, that's always a bug.

**Comment by ChrisRackauckas** [comment]
`mapreduce` is also one for this list?

**Comment by maleadt** [comment]
@jekbradbury has already contributed an optimized implementation, but I'm unsure about the performance. Need to have a closer look.
