### ISSUE TITLE
`sum` is hitting GPUArrays and being performed on the CPU

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CuArrays.jl#453]
```julia
using CuArrays, Profile
A = cu(rand(100))
Profile.clear()
Profile.@profile for i in 1:100000 sum(A) end
Juno.profiler()
```

shows that it's all in https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/mapreduce.jl#L169-L188

**Comment by ChrisRackauckas** [comment]
Simple implementations are giving me Inf:

```julia
using CuArrays
CuArrays.sum(x::CuArray{T}; dims=:) where T = CuArrays._reduce(+, x, typemax(T), dims)
CuArrays.prod(x::CuArray{T}; dims=:) where T = CuArrays._reduce(*, x, typemax(T), dims)
A = cu(rand(100))
sum(A) #215 
```

```julia
@noinline ODE_DEFAULT_NORM(u::AbstractArray,t) = sqrt(real(sum(UNITLESS_ABS2,u)) / length(u))
@noinline UNITLESS_ABS2(x) = real(abs2(x))

using CuArrays
A = rand(100)
B = cu(A)
t = 0.0
Base.sum(f,A::CuArray) = reduce((x,y)->UNITLESS_ABS2(x) + UNITLESS_ABS2(y),A,init=zero(eltype(A)))
ODE_DEFAULT_NORM(A,t)
ODE_DEFAULT_NORM(B,t) # Inf
```

**Comment by maleadt** [comment]
For your first issue, GPUArrays decides it's better to execute the sum on the CPU... https://github.com/JuliaGPU/GPUArrays.jl/blob/764e5680df5b3444dacde35a7969b7ab670d4020/src/mapreduce.jl#L179-L182

For the second issue, your alternative `sum` function isn't equivalent to the call to reduce, not on the GPU either:

```
ODE_DEFAULT_NORM(u::AbstractArray) = sum(UNITLESS_ABS2, u)
UNITLESS_ABS2(x) = abs2(x)

function main()
    A = rand(100)

    println(sum(UNITLESS_ABS2, A))
    println(reduce((x,y)->UNITLESS_ABS2(x) + UNITLESS_ABS2(y), A, init=zero(eltype(A))))
end
```
```
julia> main()
38.88136604774683
Inf
```

**Comment by ChrisRackauckas** [comment]
I guess this is what I am trying to do:

```julia
ODE_DEFAULT_NORM(u::AbstractArray) = sum(UNITLESS_ABS2, u)
UNITLESS_ABS2(x) = abs2(x)

function main()
    A = rand(100000)

    println(sum(UNITLESS_ABS2, A))
    println(reduce((x,y)->x + UNITLESS_ABS2(y), A, init=zero(eltype(A))))
end

main()
```

The vector will be large enough in practice that the heuristic will want to do it on the GPU.

**Comment by maleadt** [comment]
> The vector will be large enough in practice that the heuristic will want to do it on the GPU.

Then the heuristic will decide to run it on the GPU.

> I guess this is what I am trying to do:
>> (x,y)->x + UNITLESS_ABS2(y)

That reduction operation isn't associative, and the order of evaluation does not match Base's (but is implementation defined, as per the docstring of `Base.reduce`).
