### ISSUE TITLE
CuArrays downgrades CUDAapi, CUDAdrv, and CUDAnative

### ISSUE THREAD

**Issue by jianghaizhu** [JuliaGPU/CuArrays.jl#46]
`CuArrays` downgrades CUDAapi to 0.2.1, CUDAdrv to 0.6.1, and CUDAnative to 0.5.3, just like `CUDNN` does, which causes problem of tests in `CUDAnative`. JuliaGPU/CUDAnative.jl#144, JuliaGPU/CUDNN.jl#13.

**Comment by maleadt** [comment]
Fixed on master.
