### ISSUE TITLE
Bump package version more often?

### ISSUE THREAD

**Issue by Sleort** [JuliaGPU/CuArrays.jl#469]
**Is your feature request related to a problem? Please describe.**
At the moment, there are 222 commits to `CuArrays#master` since the last release, many of them fixing minor -- but significant -- issues and bugs. The large number of unreleased updates means that it is rather inconvenient to use anything but master in my daily work. This, however, is not optimal from the point of stability, as master is continuously updated and revised (thus more often breaking stuff, ref. [this issue](https://github.com/FluxML/Flux.jl/issues/917#issuecomment-549210365 ) over at Flux)

**Describe the solution you'd like**
I wonder if it would be possible to bump the package version (minor versions) more often, making it easier to ripe the benefits of (relatively) recent improvements without being subject to the "dangers of master"? I understand that this can sometimes be difficult/inconvenient for the core developers, but when possible, I think it would be nicer to everyone in the long run... (See also [this blog post](https://white.ucc.asn.au/2019/09/28/Continuous-Delivery-For-Julia-Packages.html))

Regardless: thank you for your great work!

**Comment by maleadt** [comment]
Sure, I'll try and keep the releases smaller. The reason the current release, which I'm currently finalizing, is so big: there's some breaking changes (fairly minor changes, but breaking nonetheless) that warrant a major version bump, and there's some coupling with other GPU packages that all need a release too.

**Comment by Sleort** [comment]
Thank you. That sounds great.

But just wondering: in a similar situation in the future, would it be possible to release minor commits like, say, #378, separately, without having to wait for the major changes to be completed? In that way, one wouldn't have smaller bug fixes etc. "accidentally" being "blocked" for a long time by the longer-term release...

**Comment by maleadt** [comment]
Maybe I should now do a quick minor release so that users who don't upgrade Flux at least get a working `mse`. I'll have a look.

**Comment by Sleort** [comment]
Nice. If my memory serves me, I believe there are a bunch of other commits that could be released as well (like on accumulation, reduction, and maybe more?). If it's not too much of a hassle, of course...

**Comment by maleadt** [comment]
I've included as much as possible: https://github.com/JuliaRegistries/General/pull/5026

**Comment by maleadt** [comment]
New versions have been tagged and released. I'm going to close this, and try to release a little more often. Feel free to ping me on Slack if that doesn't happen.

**Comment by Sleort** [comment]
Thanks a lot - especially for the exemplary speedy resolve!
