### ISSUE TITLE
CuArrays 1.4.0 fails to initialize on windows

### ISSUE THREAD

**Issue by alandion** [JuliaGPU/CuArrays.jl#473]
similar to <https://github.com/JuliaGPU/CUDAdrv.jl/issues/174>, the CuArrays `__init__` fails on windows with 

```
┌ Error: CuArrays.jl failed to initialize; the package will not be functional.
│ To silence this message, import with ENV["CUDA_INIT_SILENT"]=true,
│ and be sure to inspect the value of CuArrays.functional().
│   exception =
│    error compiling __hidden_init__: error compiling version: could not load library "libcublas"
│    The specified module could not be found
```

although CUDAapi.find_cuda_library("cublas", find_toolkit()) succeeds in finding the relevant cublas library, the library file is then assumed to be "libcublas" which is not the case on windows

**Comment by maleadt** [comment]
What is the name of the CUBLAS library on Windows then?
