### ISSUE TITLE
Flux.jl works with CuArrays 1.4.4, but not 1.4.5

### ISSUE THREAD

**Issue by Sleort** [JuliaGPU/CuArrays.jl#496]
**Describe the bug**
This may be a bug in Flux, but since I'm almost sure it's related to the change in CuArrays (and dependencies) going from v1.4.4 to v1.4.5, I'll report it here... (After all, minor updates shouldn't be breaking.)

In short, Flux (master) works fine with CuArrays 1.4.4, but gives the message
```julia
julia> using Flux
┌ Warning: CUDA GPU available, but CuArrays.jl failed to load
└ @ Flux ~/.julia/packages/Flux/bqklb/src/Flux.jl:48
```
with 1.4.5.

**Environment details**
Details on Julia:
```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Julia packages:
 - CuArrays.jl: v1.4.5
 - CUDAnative.jl: v2.5.5

CUDA: toolkit and driver version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by maleadt** [comment]
Sorry about that. This is CUDAdrv failing to load. Which version are you using? What's the output of `using CUDAdrv` and doing the same with the `JULIA_CUDA_VERBOSE` environment variable set to `true`?

**Comment by maleadt** [comment]
Oh sorry, this is indeed CuArrays.jl failing to load, my mistake. Could you do the same (`JULIA_CUDA_VERBOSE=true`, `using CuArrays`) for CuArrays?

**Comment by maleadt** [comment]
Actually, I can reproduce. I'll look at it.

**Comment by Sleort** [comment]
Thanks!
