### ISSUE TITLE
GC preserve in generated ccall

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CuArrays.jl#503]
Since we often pass CuArrays to the low-level wrapper functions, I wonder if it'd make sense to `GC.@preserve` every input around each generated ccall. Adds some safety and if it is indeed redundant, it should have negligible cost. Any thoughts?

**Comment by maleadt** [comment]
Not necessary: https://github.com/FluxML/Flux.jl/issues/923#issuecomment-555446209
