### ISSUE TITLE
Tutorial initial benchmark times/text don't make sense

### ISSUE THREAD

**Issue by scottstanie** [JuliaGPU/CuArrays.jl#519]
I can move this to discourse if an issue is not the right location.

**Describe the bug**

From the tutorial https://juliagpu.gitlab.io/CuArrays.jl/tutorials/generated/intro/

<img width="792" alt="image" src="https://user-images.githubusercontent.com/8291800/69691188-f5e6c500-1093-11ea-9a7b-85915c95e5b7.png">
The parallel time is slower despite the saying there's a performance benefit.

The GPU section doesn't match as well:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/8291800/69691256-26c6fa00-1094-11ea-8538-2dcc45e96b42.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/8291800/69691265-2c244480-1094-11ea-951f-94514cda2932.png">

I assume that the GPU version is supposed to be faster, but also on my machine it's only barely faster than the sequential (but that may be a separate issue).
Is the problem here how the documentation is being built? Maybe it's running the code in an odd environment?

**Comment by maleadt** [comment]
Fixed in https://juliagpu.gitlab.io/CUDA.jl/tutorials/introduction/
