### ISSUE TITLE
cu(x) always returns Float32

### ISSUE THREAD

**Issue by kazimuth** [JuliaGPU/CuArrays.jl#540]
```
$ CuArray(zeros(UInt8, 1))
1-element CuArray{UInt8,1,Nothing}:
 0x00
$ cu(zeros(UInt8, 1))
1-element CuArray{Float32,1,Nothing}:
 0.0
```

This may be the expected behavior but I found it kinda confusing.

**Comment by maleadt** [comment]
By design. A questionable one, but it would be too breaking to change at this point. Use the CuArray constructor, or `adapt(CuArray, ...)` if you want the recursive behavior.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/commit/59cf2c6e1e56c7a779d347e79bbd5850f8c72992
