### ISSUE TITLE
resize! broken

### ISSUE THREAD

**Issue by kose-y** [JuliaGPU/CuArrays.jl#547]
**Describe the bug**
`resize!` falls back to GPUArrays implementation and then fails, with error message "buffer not defined"

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
using CuArrays
y = cu([1, 3, 5])
resize!(y, 10)
```
```
UndefVarError: buffer not defined

Stacktrace:
 [1] resize!(::CuArray{Float32,1}, ::Tuple{Int64}) at /home/kose/.julia/packages/GPUArrays/J4c3Q/src/vectors.jl:8
 [2] resize!(::CuArray{Float32,1}, ::Int64) at /home/kose/.julia/packages/GPUArrays/J4c3Q/src/vectors.jl:4
 [3] top-level scope at In[82]:3
```
**Expected behavior**
resize theh vector `y` to size 10.

**Environment details (please complete this section)**
Details on Julia:
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
```

Julia packages:
- CUDAdrv v3.1.0
- CUDAnative v2.3.0
- CuArrays v1.2.1
- GPUArrays v1.0.1

**Comment by maleadt** [comment]
ref https://github.com/JuliaGPU/GPUArrays.jl/issues/184
