### ISSUE TITLE
ReshapedArray causes scalar indexing

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CuArrays.jl#548]
```julia
using CuArrays
CuArrays.allowscalar(false)
dp = cu(ones(252)')
p  = cu(ones(252))
reshape(dp,size(p)) # Error
vec(dp) # Error
```

**Comment by maleadt** [comment]
Dup of https://github.com/JuliaGPU/CuArrays.jl/issues/508. You're working with a `ReshapedArray{Float32,1,LinearAlgebra.Adjoint{Float32,CuArray{Float32,1,Nothing}}`.

**Comment by ChrisRackauckas** [comment]
Is there a way to concretize this? A copy or something as a workaround?

**Comment by maleadt** [comment]
You can pass the Adjoint to the CuArray constructor to materialize it. Or add the necessary method to have it actually dispatch to what you want (or select the GPU BroadcastStyle).

**Comment by ChrisRackauckas** [comment]
The issue here is that I don't know if it's a CuArray. Is this something that needs Adapt.jl?

**Comment by ChrisRackauckas** [comment]
Dope, the easiest workaround for me was just `dp'` haha, take care.
