### ISSUE TITLE
vcat Error

### ISSUE THREAD

**Issue by DavidBegert** [JuliaGPU/CuArrays.jl#55]
using CuArrays

x = cu(rand(2))
y = cu(rand(2))
vcat(x,y)

Gives me warnings and error: 
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_box_uint32",   %59 = call i8** @jl_box_uint32(i32 zeroext %58), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_gc_pool_alloc",   %60 = call i8** @jl_gc_pool_alloc(i8* %ptls_i8, i32 1456, i32 32), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %63 = call i8** @jl_apply_generic(i8*** %9, i32 3), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %64 = call i8** @jl_apply_generic(i8*** %12, i32 2), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %66 = call i8** @jl_apply_generic(i8*** %4, i32 4), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %67 = call i8** @jl_f_getfield(i8** null, i8*** %7, i32 2), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %68 = call i8** @jl_f_getfield(i8** null, i8*** %11, i32 2), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %70 = call i8** @jl_apply_generic(i8*** %5, i32 4), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %71 = call i8** @jl_f_getfield(i8** null, i8*** %15, i32 2), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %72 = call i8** @jl_f_getfield(i8** null, i8*** %16, i32 2), !dbg !17))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_apply_type",   %78 = call i8** @jl_f_apply_type(i8** null, i8*** %8, i32 4), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_box_int64",   %79 = call i8** @jl_box_int64(i64 signext %0), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_gc_pool_alloc",   %80 = call i8** @jl_gc_pool_alloc(i8* %ptls_i8, i32 1432, i32 16), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_new_structv",   %86 = call i8** @jl_new_structv(i8** %78, i8*** %13, i32 3), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %87 = call i8** @jl_apply_generic(i8*** %6, i32 2), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_tuple",   %88 = call i8** @jl_f_tuple(i8** null, i8*** %10, i32 1), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_tuple",   %89 = call i8** @jl_f_tuple(i8** null, i8*** %14, i32 2), !dbg !23))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %53 = call i8** @jl_f_getfield(i8** null, i8*** %11, i32 2), !dbg !31))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %54 = call i8** @jl_f_getfield(i8** null, i8*** %12, i32 2), !dbg !31))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_gc_pool_alloc",   %55 = call i8** @jl_gc_pool_alloc(i8* %ptls_i8, i32 1480, i32 48), !dbg !32))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %58 = call i8** @jl_apply_generic(i8*** %14, i32 3), !dbg !32))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_f_getfield",   %59 = call i8** @jl_f_getfield(i8** null, i8*** %13, i32 2), !dbg !32))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %60 = call i8** @jl_apply_generic(i8*** %15, i32 3), !dbg !32))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_gc_pool_alloc",   %61 = call i8** @jl_gc_pool_alloc(i8* %ptls_i8, i32 1432, i32 16), !dbg !32))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_box_uint32",   %65 = call i8** @jl_box_uint32(i32 zeroext %30), !dbg !32))
WARNING: Encountered incompatible LLVM IR for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0: CUDAnative.InvalidIRError("calls the Julia runtime", ("jl_apply_generic",   %66 = call i8** @jl_apply_generic(i8*** %10, i32 5), !dbg !32))

ERROR: LLVM IR generated for kernel(Int64, CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at capability 6.1.0 is not compatible
Stacktrace:
 [1] #compile_function#58(::Bool, ::Function, ::Any, ::Any, ::VersionNumber) at /home/david/.julia/v0.6/CUDAnative/src/jit.jl:422
 [2] cufunction(::CUDAdrv.CuDevice, ::Any, ::Any) at /home/david/.julia/v0.6/CUDAnative/src/jit.jl:476
 [3] macro expansion at /home/david/.julia/v0.6/CUDAnative/src/execution.jl:108 [inlined]
 [4] _cuda(::Tuple{Int64,Int64}, ::Int64, ::CUDAdrv.CuStream, ::CuArrays.#kernel#10, ::Int64, ::CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}, ::Tuple{CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global},CUDAnative.CuDeviceArray{Float32,1,CUDAnative.AS.Global}}) at /home/david/.julia/v0.6/CUDAnative/src/execution.jl:80
 [5] _cat(::Int64, ::CuArray{Float32,1}, ::CuArray{Float32,1}, ::Vararg{CuArray{Float32,1},N} where N) at /home/david/.julia/v0.6/CuArrays/src/utils.jl:95
 [6] cat_t(::Int64, ::Type{T} where T, ::CuArray{Float32,1}, ::CuArray{Float32,1}, ::Vararg{CuArray{Float32,1},N} where N) at /home/david/.julia/v0.6/CuArrays/src/utils.jl:103
 [7] vcat(::CuArray{Float32,1}, ::CuArray{Float32,1}) at /home/david/.julia/v0.6/CuArrays/src/utils.jl:106

I built Julia 0.6.2 from source and am running on Ubuntu 16.04. GPU is 1060 GEFORCE (compute capability 6.1.0) and I am running CUDA 8.0 with CUDNN 7.0.5
Has anyone seen this error before? Any help would be greatly appreciated! :)

**Comment by MikeInnes** [comment]
Is this still the case on the latest release?

**Comment by DavidBegert** [comment]
Seems to work when I checkout to v0.5.0 of CuArrays. 
Thanks!
