### ISSUE TITLE
CuArrays looks for the wrong version of cuDNN on windows10

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaGPU/CuArrays.jl#587]
**Describe the bug**
CuArrays does not find the dll for cudnn on windows 10. Enabling of debug information reveals that it looks for the following filenames:
`Debug: Looking for library cudnn64, cudnn, cudnn64_10, cudnn64_102`

However, the version of cuDNN which works with CUDA 10.2 is version 7.6 and the precompiled files downloadable from NVIDIAS homepage name the file cudnn64_7.dll.

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
julia> using CuArrays

julia> CuArrays.has_cudnn()
false
```

**Expected behavior**
Find cudnn so that has_cudnn() returns true.

**Build log**
```
# Not applicable I guess...
```

**Environment details (please complete this section)**
Details on Julia:
```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_DEPOT_PATH = E:/Programs/julia/.julia
  JULIA_NUM_THREADS = 6
```

Julia packages:
 - CuArrays.jl:
 - CUDAnative.jl:
 - ...

CUDA: 10.2, cudnn 7.6.5

**Additional context**
Temporary workaround is to create a copy of cudnn64_7.dll which matches one of the tried names (well duh!).

**Comment by maleadt** [comment]
Thanks for the report, I know what's up. Will push a fix and tag a release tomorrow.
