### ISSUE TITLE
Make CURAND seeding more consistent with Base

### ISSUE THREAD

**Issue by marius311** [JuliaGPU/CuArrays.jl#589]
There's two improvement I wonder if could be made. The first is that `CURAND.seed!()` doesn't seem to do anything, or, at least, it doesn't do what `Random.seed!()` does. I was expecting it would reseed based on some machine entropy source, but afaict it doesn't. For example, when I run this script on a machine with two GPUs, both print out the exact same random numbers every time, indicating to me that `CURAND.seed!()` on each did not reseed them independently (nor really, at all):

```julia
# test.jl

using CUDAdrv, Distributed
addprocs(2)
@everywhere workers() begin
    using CUDAnative, CuArrays
end

# assign devices
asyncmap((zip(workers(), devices()))) do (p, d)
    remotecall_wait(p) do
        @info "Worker $p uses $d"
        device!(d)
        CuArrays.CURAND.seed!()
        @show CuArrays.CURAND.rand(Float64, 1)[1]
    end
end
```

```
julia test.jl 
[ Info: Worker 2 uses CuDevice(0): Tesla V100-SXM2-16GB
[ Info: Worker 3 uses CuDevice(1): Tesla V100-SXM2-16GB
      From worker 2:	(CuArrays.CURAND.rand(Float64, 1))[1] = 0.4384508447184235
      From worker 3:	(CuArrays.CURAND.rand(Float64, 1))[1] = 0.4384508447184235
```

The second request would be that, assuming the above could done, that this was automatically done for new devices. This would be consistent with how Base reseeds new processes:

```julia
# fresh session

julia> using Distributed

julia> addprocs(2)

julia> pmap(workers()) do i
           (i,rand())
       end
2-element Array{Tuple{Int64,Float64},1}:
 (2, 0.17172315101410618)
 (3, 0.8353871151893553) 
```

or even threads:

```julia
# fresh session

julia> map(fetch,[Threads.@spawn((Threads.threadid())) for i=1:2])
2-element Array{Int64,1}:
 2
 2
# ^ first spawn call always runs both on thread 2 for some reason

julia> map(fetch,[Threads.@spawn((Threads.threadid(),rand())) for i=1:2])
2-element Array{Tuple{Int64,Float64},1}:
 (1, 0.8670538288134255)
 (2, 0.7810143871387158)

```

**Comment by maleadt** [comment]
PRs are up to improve this, please have a look. `CuArrays.seed!` (with an optional seed value) now seeds both the CuArrays and GPUArrays RNGs; and the underlying `Random.seed!` calls now behave like the Random stdlib.
