### ISSUE TITLE
LLVM Problem

### ISSUE THREAD

**Issue by maxMel1** [JuliaGPU/CuArrays.jl#61]
i am using Julia 0.6.2 in Atom (GTX 1060, Cuda installed, Ryzen 5 1600X)
I know i cant use the newest Version in 0.6.2, but if i install CuArrays it will install an older Version of LLVM automatically, but i get a LoadError:

```
===[ ERROR: LLVM ]===
LoadError: Unknown OS
while loading C:\Users\Max.julia\v0.6\LLVM\deps\build.jl, in expression starting on line 104

Part of the Problem:
INFO: Building CUDAnative
ERROR: LoadError: ArgumentError: Module Unicode not found in current path.
Run Pkg.add("Unicode") to install the Unicode package.

if i install the knewest version of LLVM:
Pkg.test("CuArrays") gives:
WARNING: julia is fixed at 0.6.2 conflicting with requirement for LLVM: [0.7.0-DEV.2915,∞)
```

How can i solve this Problem without Julia 0.7?

**Comment by vchuravy** [comment]
please don't cross-post https://github.com/maleadt/LLVM.jl/issues/90

What OS are you running on? What do you mean by "newest version of LLVM" did you do a manual `Pkg.checkout`?

**Comment by maleadt** [comment]
> What OS are you running on? 

Presumable Windows.

https://github.com/maleadt/LLVM.jl/issues/90#issuecomment-374355739
