### ISSUE TITLE
Where can I find All the using instructions of CuArrays?

### ISSUE THREAD

**Issue by ajsagit** [JuliaGPU/CuArrays.jl#668]
**Is your feature request related to a problem? Please describe.**
I read the doc and almost all the src code. But still can not find the all instructions.
How many functions in CuArrays?
What are they?
How to use them?

**Describe the solution you'd like**
Wonderful document. Or instructions.

**Describe alternatives you've considered**
Note in the code

**Additional context**
e.g. CuArrays.zeros where is it from?

TIA

**Comment by ali-ramadhan** [comment]
Hi @ajsagit, not a developer but a few links to get you started:
https://juliagpu.org/cuda/
https://juliagpu.org/learn/

Maybe this is the documentation you are looking for? https://juliagpu.gitlab.io/CUDA.jl/

If you're looking for the CuArrays.jl API documentation it is here: https://juliagpu.gitlab.io/CuArrays.jl/

`CuArrays.zeros` does not have a docstring so it's not in the API documentation but you can find the definition here: https://github.com/JuliaGPU/CuArrays.jl/blob/1ec6c0cba549c27da9eea68e90d08ab9df181ba4/src/array.jl#L337

You can locate functions with the `@functionloc` macro. For example:
```julia
julia> @functionloc CuArrays.zeros(10)
("/home/alir/.julia/packages/CuArrays/1njKF/src/array.jl", 321)
```

To be fair, it might not be the easiest thing to find the API docs as the only link is through a badge in the CuArrays.jl README, but if you think it's not visible enough then you should open an issue on CuArrays.jl to discuss ways of making the API docs more visible.

It would be great if _wonderful_ documentation just appeared but writing good documentation is hard work and (at least partially) community-driven for open-source projects like Julia's GPU stack. The documentation is still a work-in-progress but if you have suggestions for what should be added, e.g. docstrings for exported functions such as `CuArrays.zeros`, then please chime in at https://github.com/JuliaGPU/CUDA.jl/issues/5

**Comment by maleadt** [comment]
Thanks for linking to some resources @ali-ramadhan! @ajsagit, please use Discourse or Slack for questions, the bug tracker is for filing issues.

**Comment by ajsagit** [comment]
Thank you so much!
