### ISSUE TITLE
add implicit float conversion to math functions 

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGPU/CuArrays.jl#671]
As mentioned by @maleadt in https://github.com/FluxML/Zygote.jl/pull/574:
"""
Oh right, that was one breaking change in the CuArrays release: Integers used to be eagerly converted by cu to Float32. That's more than questionable, so we got rid of it. However, many NVIDIA intrinsics are not available for integers, so that broke some tests.
"""
I wonder what is the rationale of the conversion removal and if we could re-introduce the old behavior, which is also what Base does, as it may be convenient in some situations.

**Comment by maleadt** [comment]
> which is also what Base does

Wait, what? No, Base doesn't do any eager conversions. Having `cu([1]) == [1f0]` seems like a recipe for disaster, why do you want that conversion back? The fact that you were silently dispatching to floating-point operations when asking for (unsupported) integer versions is an argument for the current behavior, to me.

**Comment by CarloLucibello** [comment]
sorry I meant Base converts when doing mathematical operations such as `log.([1, 1])`, so I would expect the same for `log.(cu([1, 1]))`

**Comment by CarloLucibello** [comment]
I see now that on CuArrays 1.7 `cu` performed the casting, I agree that should be avoided and current behavior for `cu` is preferable. On the other hand, I'd like all mathematical operations to work on integer cuarrays through conversion

**Comment by maleadt** [comment]
> I'd like all mathematical operations to work on integer cuarrays through conversion

Yeah, understandably. We're  in the annoying situation now where we've been hoping to reuse Base's conversions through Cassette, only redefining the bottommost calls to incompatible CPU library intrinsics with NVIDIA ones, but progress on Cassette inferability has been... slow. In the meantime, we don't have a good policy or place to add higher-level functions like `log` accepting integers. I guess we should just add them to CUDAnative for now, e.g. like https://github.com/JuliaGPU/CUDAnative.jl/pull/445. If you have the need, and the time to create a PR, feel free to add some implementations there!
