### ISSUE TITLE
Multiplication between mixed types doesn't drop leading dimensions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CuArrays.jl#673]
MWE:

```julia
using CuArrays
A = cu(-rand(3,3))
u0 = CuVector([1.0;0.0;0.0])
size(A*u0) # (3,1)
```

This seems to be a regression from pre-2.0.

**Comment by maleadt** [comment]
```
julia> CuArrays.rand(Float32, 3, 3)*CuArrays.rand(Float64, 3)
3×1 CuArray{Float64,2,CuArray{Float64,1,Nothing}}:
 0.5720983409319119
 0.8842426252295259
 1.1483806167554638

julia> CuArrays.rand(Float32, 3, 3)*CuArrays.rand(Float32, 3)
3-element CuArray{Float32,1,Nothing}:
 0.9441768
 0.8232954
 0.62073404
```

@haampie I take it this is related to the mul!/gemm refactor? It's also weird the first returns an array with a parent (a view, I guess), that shouldn't be needed here?

**Comment by haampie** [comment]
It does not dispatch to CUBLAS for mixed Float64s and Float32, so this is an issue in GPUArrays it seems:

https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/host/linalg.jl#L109-L112
