### ISSUE TITLE
Failed to detect installed CUDA version.

### ISSUE THREAD

**Issue by holmescn** [JuliaGPU/CuArrays.jl#678]
**Describe the bug**
When doing any operation at the first time, all artifacts of CUDA are downloaded included the useless ones.

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
# After installation
using CuArrays
x = CuArrays.fill(1.0, 10)
# This will trigger the artifacts downloading.
x *= 2
```

**Expected behavior**
Only the CUDA package that match the system installed NVidia CUDA Toolkit version should be installed, not all available versions.

**Build log**
`Pkg.build` is success.

**Environment details (please complete this section)**
Details on Julia:
```
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, ivybridge)
```

Julia packages:
 - CuArrays.jl:
 - CUDAnative.jl:
 - Flux.jl

CUDA: 10.0/440.44

**Comment by maleadt** [comment]
> all artifacts of CUDA are downloaded included the useless ones.

That's not true.

> Only the CUDA package that match the system installed NVidia CUDA Toolkit version should be installed, not all available versions.

The CUDA toolkit itself is downloaded, matching the installed CUDA _driver_. If you want to use your own toolkit, set JULIA_CUDA_USE_BINARYBUILDER to false.
