### ISSUE TITLE
Extend `accumulate!`

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/CuArrays.jl#68]
CuArrays has `accumulate!`, but it's limited: does not support anything but vectors, does not support the init keyword, and is slow (should use the shmem/shfl optims from https://github.com/JuliaGPU/CUDAnative.jl/blob/master/examples/scan.jl)

Old post:

@dpsanders and I just run into the situation where we wanted to do a cumsum on a CuArray.

CUDAnative has it as a example, but we should probably add the functionality to CuArrays https://github.com/JuliaGPU/CUDAnative.jl/blob/master/examples/scan.jl

**Comment by maleadt** [comment]
Maybe as a higher-order `scan(f, ..; inclusive=true)` function?

**Comment by dpsanders** [comment]
I have a (very) simple version of `cumsum` working. I can turn this into a version of `accumulate!`. Should I add this as a PR here?

**Comment by maleadt** [comment]
Yes that would be nice! Is it based on the CUDAnative example?

**Comment by ali-ramadhan** [comment]
Happy to help work on this and contribute an efficient `scan` implementation.

I'm particularly interested in an efficient non-destructive `mean(c, dims)` where `c` is a non-contiguous view as it currently devolves into scalar operations.

The scan example seems to overwrite the array. I guess to make a non-destructive version you would take the work-efficient and accumulate into a temporary array?

Currently `mean` is pretty fast but I couldn't figure out how it's implemented.

**Comment by maleadt** [comment]
Fixed by https://github.com/JuliaGPU/CuArrays.jl/pull/447
