### ISSUE TITLE
Sum, any, etc. with function is no longer implemented

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CuArrays.jl#688]
MWE:

```julia
using CuArrays
sum(abs2,cu(rand(2)))
```

I don't know when this disappeared but I know it used to since the DiffEq stuff uses it a lot and it used to be fine. I assume this is something that was missed by the new mapreduce?

**Comment by ChrisRackauckas** [comment]
Seems to be related:

```julia
any(isnan,cu(rand(2)))
```

also not implemented.

**Comment by maleadt** [comment]
These things are definitely implemented, and tested. https://github.com/JuliaGPU/GPUArrays.jl/blob/cb79e08c09ca0eb776c1ded7b7fe8876bd012981/test/testsuite/mapreduce.jl#L155

**Comment by maleadt** [comment]
Ah wait the GPUArrays release should have been breaking, I guess.

**Comment by ChrisRackauckas** [comment]
```
  [3a865a2d] CuArrays v2.0.1
  [0c68f7d7] GPUArrays v3.1.0 #master (https://github.com/JuliaGPU/GPUArrays.jl.git) 
```

**Comment by maleadt** [comment]
I'll just tag and release CuArrays too.

**Comment by ChrisRackauckas** [comment]
Oh okay, so it needs both masters right now?

**Comment by maleadt** [comment]
Yeah, this functionality just moved packages. Will also tag a CuArrays release.
