### ISSUE TITLE
compilation in Julia 0.6.2 with LLVM requiring Julia 0.7-dev

### ISSUE THREAD

**Issue by aakhmetz** [JuliaGPU/CuArrays.jl#69]
Just curious: I am trying to install CuArrays in Julia 0.6.2, but it requires LLVM. LLVM compiles out of box in Julia 0.7-dev and does not want to do that in Julia 0.6.2. The other way around: CuArrays does not want to build itself in Julia 0.7-dev.

Is there any possible way out of this circle? Or has someone succeeded recently with the build in 0.6.2? Thank you in advance

**Comment by maleadt** [comment]
> LLVM compiles out of box in Julia 0.7-dev and does not want to do that in Julia 0.6.2

It requires a manually built Julia on 0.6. That shouldn't be too much effort though, just clone the git repo, check-out the latest 0.6 tag, and run `make`. As you mention, we have worked around this requirement on 0.7.

> CuArrays does not want to build itself in Julia 0.7-dev

That is a work in progress, AFAIU @SimonDanisch has a branch for 0.7 compatibility on CuArrays/CLArrays/GPUArrays.

**Comment by SimonDanisch** [comment]
It's a work in progress:
https://github.com/JuliaGPU/CuArrays.jl/pull/70
https://github.com/JuliaGPU/GPUArrays.jl/pull/108
And currently I'm running into:
https://github.com/JuliaGPU/CUDAnative.jl/issues/180

**Comment by aakhmetz** [comment]
Thank you!

> It requires a manually built Julia on 0.6. That shouldn't be too much effort though, just clone the git repo, check-out the latest 0.6 tag, and run make. As you mention, we have worked around this requirement on 0.7.

I tried to do it (clone the repo from git, then run make), but I've got other errors such as "@debug is unknown" or "module Test cannot be found in 0.6". Probably and due to my experience, it's better if I wait for a stable future release of 0.7 :-)
