### ISSUE TITLE
Package fails to load

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CuArrays.jl#732]
```julia
julia> using CuArrays
[ Info: Precompiling CuArrays [3a865a2d-5b23-5a0f-bc46-62713ec82fae]
ERROR: LoadError: LoadError: LoadError: UndefVarError: AddrSpacePtr not defined
```

This is on Julia 1.5-rc1 on linux; I assume it's easy to reproduce but can try to provide more detail if not.

**Comment by maleadt** [comment]
Yeah, experimental stuff got renamed. Fixed in CUDA.jl.

**Comment by MikeInnes** [comment]
Seems to be 1.5-only, so things still run on current release. Still, it'd be nice to be able to load current Flux on 1.5 when it comes out. Is it really the plan to just drop CuArrays entirely? That seems to assume a very smooth and quick ecosystem upgrade to CUDA.jl.

**Comment by maleadt** [comment]
> Is it really the plan to just drop CuArrays entirely?

Correct. CUDA.jl should be a drop in replacement, and only people using 1.5 would run into this. Can just have a look to strip the offending functionality, as a workaround (it's only used for tensor core support).

**Comment by maleadt** [comment]
Should be fixed with https://github.com/JuliaRegistries/General/pull/17342. Can you verify?
