### ISSUE TITLE
GPU memory hog

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CuArrays.jl#79]
The current pool allocator never frees memory except when allocations fail. This quickly leads to CuArrays/Flux using all of the available memory, as frequently observed on `cyclops`. We should probably have an idle thread scan for unused pool entries and free those up.

**Comment by jekbradbury** [comment]
Never freeing except on OOM is also the current behavior of other imperative deep learning frameworks (Chainer, PyTorch) because the latency of `cudaMalloc` is just so terrible that they want to avoid it at all costs.

**Comment by maleadt** [comment]
I was thinking of either freeing upon alloc, or an idle task (if free latency is high too), possibly with async API calls to reduce latency even further. Alternatively, if that turns out too slow, we can have a different limit specified by eg. environment variable.
