### ISSUE TITLE
Speed Issue with CuBLAS gemm_batched

### ISSUE THREAD

**Issue by avik-pal** [JuliaGPU/CuArrays.jl#93]
I was trying to use the CuArrays wrapper for gemm_batched. However, I am encountering some speed issues.
```julia
z = [cu(rand(224*224, 5)) for i in 1:100]
@btime begin
    CuArrays.BLAS.gemm_batched('T', 'N', z, z)
    CUDAnative.synchronize()
end
```
This returns `14.938 ms (856 allocations: 27.11 KiB)`
```julia
bmm(x, y) = [x[i]' * y[i] for i in 1:length(x)]
@btime begin
    bmm(z, z)
    CUDAnative.synchronize()
end
```
While this gets executed in `4.997 ms (1106 allocations: 46.31 KiB)`
```julia
versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
```julia
Pkg.status("CuArrays")
- CuArrays                      0.6.2+             master
```
Benchmarks performed on a 1080Ti 12 GB GPU

**Comment by MikeInnes** [comment]
Can you profile and see where the time is spent? If it's not all in `synchronize`, that points to an issue in our wrapper.

**Comment by avik-pal** [comment]
It spends more time than Synchronize in these processes `cuCtxDestroy, cudaStreamCreateWithFlags, cudaFree,  cuCtxCreate, cuDevicePrimaryCtxRelease,  cuModuleUnload, cuMemAlloc`. But I guess these are quite the standard function calls

**Comment by andreasnoack** [comment]
Wasn't the conclusion from the Slack discussion that the right interface for batched gemm was https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemmstridedbatched? I guess the current interface could be spending a lot of time on many small allocations instead of a single big one.

**Comment by MikeInnes** [comment]
Ok, in that case it's not worth spending time on this wrapper. I've opened #95 to track the new wrapper.
