### ISSUE TITLE
copy! is buggy because there is no `ptr`

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/CuArrays.jl#97]
Hi,

I am using CuArrays but the following operation seems unsupported:

```julia
using CuArrays
x=rand(10) |> cu;
CuArrays.allowscalar(false)
V[:,1] .= x;
```

It gives:

`ERROR: scalar getindex is disabled`

Using copy! from [link](https://github.com/JuliaGPU/CuArrays.jl/blob/7d13934e9c47f2b15a83c399d610e0bc5a4ddc3d/src/gpuarray_interface.jl#L95)  is troublesome because a CuArray does not have `ptr` in its `struct`.

Is there a way around?

Thank you for your help.

**Comment by maleadt** [comment]
That `.ptr` doesn't exist anymore, so the `copy!` functions should work as excepted.
